name: app_attest_integrity
description: "A Flutter plugin to assess an app integrity. Uses App attest on iOS and app Integrity on Android."
version: 2.0.0
homepage: https://github.com/bamlab/app_attest_integrity
repository: https://github.com/bamlab/app_attest_integrity

environment:
  sdk: ^3.10.1
  flutter: '>=3.32.2'

dependencies:
  code_assets: ^1.0.0
  crypto: ^3.0.7
  ffi: ^2.1.5
  flutter:
    sdk: flutter
  hooks: ^1.0.0
  jni: ^0.15.2
  logging: ^1.3.0
  native_toolchain_c: ^0.17.4
  objective_c: ^9.1.0
  plugin_platform_interface: ^2.0.2
  retry: ^3.1.2

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  jnigen: ^0.15.0
  melos: ^6.3.3
  theodo_analysis: ^1.5.0

flutter:
  plugin:
    platforms:
      android:
        package: com.theodo.app_attest_integrity
        pluginClass: AppAttestIntegrityPlugin
      ios:
        ffiPlugin: true
